###TCSS600A - Independent study Project         ###
###  Author: Sumitha Ravindran                  ###
### Recipe Box Application                      ###
### Deployment file: Delete_a_Recipe            ###
### Endpoint to delete a recipe from recipe_box ###
---
apiVersion: v1
kind: Service
metadata:
  name: delete-latency-service
  labels:
    app: delete-latency
spec:
  type: LoadBalancer
  ports:
  - port: 8010
    targetPort: 8010
    protocol: TCP
    name: http
  selector:
    app: delete-latency
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: delete-latency-deployment
  labels:
    app: delete-latency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-latency
  template:
    metadata:
      labels:
        app: delete-latency
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8010'
        prometheus.io/path: '/recipe_box/delete/metrics'
    spec:
      containers:
      - name: delete-latency
        image: sr/delete_latency:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: LISTENING_PORT
            value: "8010"