###TCSS600A - Independent study Project            ###
###  Author: Sumitha Ravindran                     ###
### Recipe Box Application                         ###
### Deployment file: online suggestion             ###
### Endpoint to get online suggestion for recipes  ###
---
apiVersion: v1
kind: Service
metadata:
  name: suggestion-latency-service
  labels:
    app: suggestion-latency
spec:
  type: LoadBalancer
  ports:
  - port: 9060
    targetPort: 9060
    protocol: TCP
    name: http
  selector:
    app: suggestion-latency
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: suggestion-latency-deployment
  labels:
    app: suggestion-latency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suggestion-latency
  template:
    metadata:
      labels:
        app: suggestion-latency
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9060'
        prometheus.io/path: '/suggestion/metrics'
    spec:
      containers:
      - name: suggestion-latency
        image: sr/suggestion_latency:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: LISTENING_PORT
            value: "9060"